### ISSUE TITLE
please provide release notes

### ISSUE THREAD

**Issue by tcurdt** [PDF-Archiver/PDF-Archiver#44]
I am looking for the last version before the macOS 11 requirement.
Would be nice to be able to find that in some release notes.

**Comment by JulianKahnert** [comment]
Hi @tcurdt 
you are right!

There has been a transition because I want a single codebase for the iOS and macOS App. You can still download and use PDF Archiver 1 for free:
https://apps.apple.com/de/app/pdf-archiver-1/id1352719750?mt=12

If you want to compile it yourself, you can use state in the version-1 branch:
https://github.com/PDF-Archiver/PDF-Archiver/tree/version-1

That said, there are some performance bugs in that legacy version, which are fixed in the current version of PDF Archiver:
https://apps.apple.com/de/app/pdf-archiver/id1433801905

**Comment by tcurdt** [comment]
Bummer. I am still stuck on 10.15.7 for now (waiting for a new machine in the fall) and Archiver 1 is a bit bare bones.
Most importantly it also saves the tags as keywords :-/ I really didn't see a setting there ;)
Maybe I could disable the feature in code and do my own build *shrug*.

I tried to see if back porting the develop branch could be an option - but that's too much (useless) work.

**Comment by JulianKahnert** [comment]
Sorry to hear that but you are probably right...

**Comment by tcurdt** [comment]
I built the Archiver 1 and just removed the tag saving :)
